# Generated by Django 3.2.4 on 2022-01-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_pic',
            field=models.ImageField(default='pic/default.png', upload_to='pic/'),
        ),
    ]
